Improve test regex for new lines
amake/flutter.el pull request #11
Opened 2020-04-02 14:01 UTC by ericdallo

After using `flutter-test-at-point` a while, I noticed that's pretty common to `dartfmt` indent the test file adding a new line when the test name it's long:

So this:
```dart
testWidgets('Should open the first screen, click on button when filling the text field.', (tester) async {
...
});
```

became this:
```dart
testWidgets(
      'Should open the first screen, click on button when filling the text field.',
      (tester) async {
        ...
    });
```

This PR adds support for this corner case.

2020-04-02 14:02 UTC, ericdallo commented
@amake

2020-04-02 14:16 UTC, amake requested changes
Nice catch. Let’s hope you don’t also start seeing
```dart
'adjacent' ' ' 'strings'
```
or
```dart
'''real
multiline
strings'''
```

2020-04-02 14:16 UTC, amake commented on flutter.el
> +  (concat "^[ \t]*\\(?:testWidgets\\|test\\|group\\)([\n]*[ \t]*"
`[\n]` can be replaced with `\n`, but you might as well throw it into the class with ` \t` while you’re at it.

2020-04-02 14:55 UTC, ericdallo commented
> Nice catch. Let’s hope you don’t also start seeing
> 
> ```dart
> 'adjacent' ' ' 'strings'
> ```
> 
> or
> 
> ```dart
> '''real
> multiline
> strings'''
> ```

Yeah, I didn't see `dartfmt` indent to that, but I know that currently this is not supported and the regex would become much more complex.
I'm Ok with that, what do you think?

2020-04-03 04:13 UTC, merged

2020-04-03 04:15 UTC, amake commented
I don't think `dartfmt` can change a string's format like that, but people may choose to use them.

I agree that we shouldn't bother with them unless we later find out they're super popular.